trigger:
- master

name: Deploy Bicep files

variables:
  azureServiceConnection: '32a7a1ec-c456-46fc-989b-a707e9d27f02'
  resourceGroupName: 'rachel-function-RG03'
  location: 'eastus'
  templateFile: 'main.bicep'


steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az group create --name $(resourceGroupName) --location $(location)
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile)